version: '3.9'

services:
  getapiweather:
    container_name: getapiweather.app
    build:
      context: .
      dockerfile: app.Dockerfile
    restart: always
    command: /bin/bash ./bin/app-start.sh
    volumes:
      - .:/code
    env_file:
      - ./.env
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    container_name: getapiweather.db
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    expose:
      - 5432

volumes:
  postgres_data:
