version: '3.9'

services:
  getapiweather:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    restart: always
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=apidb
    expose:
      - 5432

volumes:
  postgres_data:
